/********************************************************************
* dsjinc_evt_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dsjinc_evt_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledsjinc_evt_dict();
extern void G__cpp_setup_inheritancedsjinc_evt_dict();
extern void G__cpp_setup_typetabledsjinc_evt_dict();
extern void G__cpp_setup_memvardsjinc_evt_dict();
extern void G__cpp_setup_globaldsjinc_evt_dict();
extern void G__cpp_setup_memfuncdsjinc_evt_dict();
extern void G__cpp_setup_funcdsjinc_evt_dict();
extern void G__set_cpp_environmentdsjinc_evt_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "dsjinc_evt.h"
#include "dsjinc_mcevt.h"
#include "ds_evt.h"
#include "ds_mcevt.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dsjinc_evt_dictLN_TClass;
extern G__linked_taginfo G__dsjinc_evt_dictLN_TBuffer;
extern G__linked_taginfo G__dsjinc_evt_dictLN_TMemberInspector;
extern G__linked_taginfo G__dsjinc_evt_dictLN_TObject;
extern G__linked_taginfo G__dsjinc_evt_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_EvtInfo;
extern G__linked_taginfo G__dsjinc_evt_dictLN_GammaInfo;
extern G__linked_taginfo G__dsjinc_evt_dictLN_GenHepEvt;
extern G__linked_taginfo G__dsjinc_evt_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dsjinc_evt_dictLN_GenParticleInfo;
extern G__linked_taginfo G__dsjinc_evt_dictLN_IPBoost;
extern G__linked_taginfo G__dsjinc_evt_dictLN_Ks0Info;
extern G__linked_taginfo G__dsjinc_evt_dictLN_Pi0Info;
extern G__linked_taginfo G__dsjinc_evt_dictLN_TrackInfo;
extern G__linked_taginfo G__dsjinc_evt_dictLN_dsjinc_evt;
extern G__linked_taginfo G__dsjinc_evt_dictLN_dsjinc_mcevt;
extern G__linked_taginfo G__dsjinc_evt_dictLN_ds_evt;
extern G__linked_taginfo G__dsjinc_evt_dictLN_ds_mcevt;

/* STUB derived class for protected member access */
